FROM alpine:3.9

RUN apk update
RUN apk add bash supervisor nginx vim iproute2

RUN rm /etc/nginx/conf.d/default.conf
COPY common/nginx.conf /etc/nginx/nginx.conf
COPY common/proxy-pass.conf /etc/nginx/conf.d/proxy-pass.conf


COPY common/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN  chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD  ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
