FROM alpine:latest

RUN apk add bash supervisor mongodb tzdata

# Install and configure MongoDB
COPY config/mongod.conf /etc/mongod.conf
RUN mkdir -p /data/db; chown mongodb:mongodb /data/db

# Supervisord
RUN mkdir /etc/supervisord.d 
COPY config/supervisord.conf /etc/supervisord.conf
COPY config/supervisord.d/mongod.ini /etc/supervisord.d/mongod.ini
