FROM alpine:3.9

RUN  apk update
RUN  apk add bash mongodb mongodb-tools tzdata

# Install and configure MongoDB
COPY alerta-db/mongod.conf /etc/mongod.conf
RUN  mkdir -p /data/db; chown mongodb:mongodb /data/db

COPY common/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN  chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD  ["/usr/bin/mongod", "-f", "/etc/mongod.conf"]
 
